# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_path": "config.ipynb",
         "DATA_PATH": "config.ipynb",
         "MODEL_PATH": "config.ipynb",
         "LR": "config.ipynb",
         "TRAIN_BATCH_SIZE": "config.ipynb",
         "VALID_BATCH_SIZE": "config.ipynb",
         "NUM_EPOCHS": "config.ipynb",
         "MAX_SEQ_LEN": "config.ipynb",
         "MODEL_NAME": "config.ipynb",
         "DEVICE": "config.ipynb",
         "TOKENIZER": "config.ipynb",
         "EntityDataset": "dataset.dataset.ipynb",
         "HasocModel": "model.model.ipynb",
         "Fitter": "utils.engine.ipynb",
         "BertFitter": "utils.engine.ipynb"}

modules = ["config.py",
           "dataset/dataset.py",
           "model/model.py",
           "utils/engine.py"]

doc_url = "https://Tendo.github.io/Bert4NER/"

git_url = "https://github.com/Tendo/Bert4NER/tree/master/"

def custom_doc_links(name): return None
